---
- hosts: test
  remote_user: root

  tasks:

  - name: Parando o serviço do Firewall
    service: name=firewalld state=stopped enabled=no

  - name: Desabilitando o SELinux
    selinux:
      state: disabled

  - name: Instalando o Apache
    yum: state=latest name={{ item }}
    with_items:
    - httpd
    - httpd-devel

  - name: Instalando o PHP
    yum: state=latest name={{ item }}
    with_items:
    - php56w
    - php56w-cli
    - php56w-common
    - php56w-pdo
    - php56w-mysqlnd
    - php56w-mbstring
    - php56w-mcrypt

  - name: Instalando o Banco de Dados
    yum: state=latest name={{ item }}
    with_items:
    - mariadb
    - mariadb-server

  - name: Starting the Database
    service: name=mariadb state=started enabled=yes

  - name: Download do IONCube
    get_url:
      url:  http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz
      dest: /tmp

  - name: Descompactando os arquivos
    shell: tar -xzf /tmp/ioncube_loaders_lin_x86-64.tar.gz -C /tmp

  - name: Copiando o Modulo
    copy:
      src: /tmp/ioncube/ioncube_loader_lin_5.6.so
      dest: /usr/lib64/php/modules

  - name: Acrescentando modulo no php.ini
    lineinfile:
      path: /etc/php.ini
      regexp: '^; If enabled, scripts may be written in encodings that are incompatible with'
      line: 'zend_extension = /usr/lib64/php/modules/ioncube_loader_lin_5.6.so'

  - name: Configurando php.ini
    lineinfile:
      path: /etc/php.ini
      regexp: '^;always_populate_raw_post_data = -1'
      line: 'always_populate_raw_post_data = -1'

  - name: Configurando php.ini
    lineinfile:
      path: /etc/php.ini
      regexp: '^;date.timezone ='
      line: 'date.timezone = America/Sao_Paulo'

  - name: Criando o Banco de Dados
    shell: echo "create database tpm_database character set utf8 collate utf8_unicode_ci;" | mysql -u root

  - name: Concedendo acesso ao Banco de Dados
    shell: echo "grant all privileges on tpm_database.* to 'tpm_user'@'localhost' identified by 't34mp455';" | mysql -u root

  - name: Flush Privileges
    shell: echo "FLUSH PRIVILEGES;" | mysql -u root

  - name: Realizando o download do TeamPasswordManager
    get_url:
      url: http://teampasswordmanager.com/assets/download/teampasswordmanager_7.73.146.zip
      dest: /tmp

  - name: Descompactando os arquivos
    shell: unzip /tmp/teampasswordmanager_7.73.146.zip -d /opt

  - name: Renomeando pasta
    shell: mv /opt/teampasswordmanager_7.73.146 /opt/teampasswordmanager

  - name: Excluindo o arquivo config.php
    shell: rm -rf /opt/teampasswordmanager/config.php

  - name: Criando o arquivo config.php
    file:
      path: /opt/teampasswordmanager/config.php
      state: touch
      mode: "u+rw,g-wx,o-wx"

  - name: Adicionando linhas no arquivo config.php
    lineinfile:
      dest: /opt/teampasswordmanager/config.php
      line: '{{ item }}'
    with_items:
      - "<?php"
      - " "
      - "// Set these database parameters before installing Team Password Manager"
      - "  "
      - "// MySQL Database server"
      - "define('CONFIG_HOSTNAME', 'localhost');"
      - "   "
      - "// User that accesses the database server, that should have all privileges on the database CONFIG_DATABASE"
      - "define('CONFIG_USERNAME', 'tpm_user');"
      - "    "
      - "// User password"
      - "define('CONFIG_PASSWORD', 't34mp455');"
      - "     "
      - "// Database for Team Password Manager. You must manually create it before installing Team Password Manager"
      - "define('CONFIG_DATABASE', 'tpm_database');"
      - "      "
      - "// Default language of the installation."
      - "// The user can change this language."
      - "// Defaults to 'en' if not used."
      - "//define('TPM_DEFAULT_LANG', 'en');"
      - "       "
      - "// Uploads folder. You can set it in two ways:"
      - "// 1. With an absolute path. Example: /var/www/domain/uploads/"
      - "// 2. With a relative path (relative to index.php). Example: ./uploads/"
      - "// Must be accessible and writable by the web server"
      - "// Define with or without trailing slash"
      - "// Defaults to ./uploads/, uncomment the following line to change this default value:"
      - "//define('UPLOADS_FOLDER' , './uploads/');"
      - "        "
      - "// For other parameters read: http://teampasswordmanager.com/docs/all-parameters-config-php/"

  - name: Criando link simbolico
    shell: ln -s /opt/teampasswordmanager /var/www/html/teampasswordmanager

  - name: Iniciando o Apache
    service: name=httpd state=started enabled=yes
