---
- hosts: test
  remote_user: root
  vars:
    userdb: tpm_user
    passdb: t34mp455
    tpmversion: "{{ lookup('file', '/tmp/tpm.version') }}"
    timezone: America/Sao_Paulo

  tasks:

  - name: Stopping the Firewall service
    service: name=firewalld state=stopped enabled=no

  - name: Disabling SELinux
    selinux:
      state: disabled

  - name: Installing Apache
    yum: state=latest name={{ item }}
    with_items:
    - httpd
    - httpd-devel

  - name: Installing PHP
    yum: state=latest name={{ item }}
    with_items:
    - php56w
    - php56w-cli
    - php56w-common
    - php56w-pdo
    - php56w-mysqlnd
    - php56w-mbstring
    - php56w-mcrypt

  - name: Installing Database
    yum: state=latest name={{ item }}
    with_items:
    - mariadb
    - mariadb-server

  - name: Starting the Database
    service: name=mariadb state=started enabled=yes

  - name: Download IONCube
    get_url:
      url:  http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz
      dest: /tmp

  - name: Unpacking the files
    shell: tar -xzf /tmp/ioncube_loaders_lin_x86-64.tar.gz -C /tmp

  - name: Copying the Module
    copy:
      src: /tmp/ioncube/ioncube_loader_lin_5.6.so
      dest: /usr/lib64/php/modules

  - name: Adding module in php.ini
    lineinfile:
      path: /etc/php.ini
      regexp: '^; If enabled, scripts may be written in encodings that are incompatible with'
      line: 'zend_extension = /usr/lib64/php/modules/ioncube_loader_lin_5.6.so'

  - name: Configuring php.ini
    lineinfile:
      path: /etc/php.ini
      regexp: '^;always_populate_raw_post_data = -1'
      line: 'always_populate_raw_post_data = -1'

  - name: Configuring php.ini
    lineinfile:
      path: /etc/php.ini
      regexp: '^;date.timezone ='
      line: 'date.timezone = {{ timezone }}'

  - name: Creating the Database
    shell: echo "create database tpm_database character set utf8 collate utf8_unicode_ci;" | mysql -u root

  - name: Concedendo acesso ao Banco de Dados
    shell: echo "grant all privileges on tpm_database.* to '{{ userdb }}'@'localhost' identified by '{{ passdb }}';" | mysql -u root

  - name: Flush Privileges
    shell: echo "FLUSH PRIVILEGES;" | mysql -u root
  
  - name: Get TPM version
    get_url:
      url: https://teampasswordmanager.com/latest-version
      dest: /tmp/tpm.version

  - name: Download TeamPasswordManager
    get_url:
      url: https://teampasswordmanager.com/assets/download/teampasswordmanager_{{ tpmversion }}.zip
      dest: /tmp

  - name: Unpacking the files
    shell: unzip /tmp/teampasswordmanager_{{ tpmversion }}.zip -d /opt

  - name: Renaming folder
    shell: mv /opt/teampasswordmanager_{{ tpmversion }} /opt/teampasswordmanager

  - name: Deleting the config.php file
    file:
      path: /opt/teampasswordmanager/config.php
      state: absent

  - name: Creating the config.php file
    file:
      path: /opt/teampasswordmanager/config.php
      state: touch
      mode: "u+rw,g-wx,o-wx"

  - name: Adding rows in the config.php file
    lineinfile:
      dest: /opt/teampasswordmanager/config.php
      line: '{{ item }}'
    with_items:
      - "<?php"
      - " "
      - "// Set these database parameters before installing Team Password Manager"
      - "  "
      - "// MySQL Database server"
      - "define('CONFIG_HOSTNAME', 'localhost');"
      - "   "
      - "// User that accesses the database server, that should have all privileges on the database CONFIG_DATABASE"
      - "define('CONFIG_USERNAME', '{{ userdb }}');"
      - "    "
      - "// User password"
      - "define('CONFIG_PASSWORD', '{{ passdb }}');"
      - "     "
      - "// Database for Team Password Manager. You must manually create it before installing Team Password Manager"
      - "define('CONFIG_DATABASE', 'tpm_database');"
      - "      "
      - "// Default language of the installation."
      - "// The user can change this language."
      - "// Defaults to 'en' if not used."
      - "//define('TPM_DEFAULT_LANG', 'en');"
      - "       "
      - "// Uploads folder. You can set it in two ways:"
      - "// 1. With an absolute path. Example: /var/www/domain/uploads/"
      - "// 2. With a relative path (relative to index.php). Example: ./uploads/"
      - "// Must be accessible and writable by the web server"
      - "// Define with or without trailing slash"
      - "// Defaults to ./uploads/, uncomment the following line to change this default value:"
      - "//define('UPLOADS_FOLDER' , './uploads/');"
      - "        "
      - "// For other parameters read: http://teampasswordmanager.com/docs/all-parameters-config-php/"

  - name: Creating symbolic link
    shell: ln -s /opt/teampasswordmanager /var/www/html/teampasswordmanager

  - name: Starting Apache
    service: name=httpd state=started enabled=yes
